[build]
  command = "pnpm -r build"
  publish = "web/build"
  base = "."

[build.environment]
  WEB_DEFAULT_API = "/api"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

